steps:
- name: 'alpine/git'
  args: [ 'clone', 'https://github.com/bridgecrewio/terragoat.git', '/workspace/terragoat' ]
- name: 'bridgecrew/checkov'
  args: [ '-d', '/workspace/terragoat/terraform/gcp' ]
# - name: 'hashicorp/terraform'
#   args: [ 'plan' ]
